apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-b

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-b
  templates:
    metadata:
      labels:
        app: hello-b
    spec:
      containers:
        - name: hello-a
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: GUNICORN_CMD_ARGS
              value: "--Capture-output --error-logfile -
                     --access-logfile - --access-logformat '%(h)s %(t)s
                    %(r)s %(s)s Host: %({Host}i)s}'"
